{% set name = "pytest-echo" %}
{% set version = "1.7.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2307af560ebbdc77967579e577f24015467fbcf80cabb9b04d225348bb8d9474

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - pytest >=2.2
    - python

test:
  imports:
    - pytest_echo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytest-echo/
  summary: pytest plugin with mechanisms for echoing environment variables, package version and generic attributes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
