{% set name = "pytest-echo" %}
{% set version = "1.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3bf6a065ca624a5915bc2a820505a44735a8aa11865a57d8214d4eac18960191

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pytest >=2.2
    - python >={{ python_min }}

test:
  imports:
    - pytest_echo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pytest-echo/
  summary: pytest plugin with mechanisms for echoing environment variables, package version and generic attributes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
