{% set name = "pytest-echo" %}
{% set version = "1.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7d765b4ddac93468fa1d303e70c48ad9e38479b4d122d5ae019919bb7fed0c2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - pytest >=2.2
    - python >={{ python_min }}

test:
  imports:
    - pytest_echo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pytest-echo/
  summary: pytest plugin with mechanisms for echoing environment variables, package version and generic attributes
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
